apiVersion: v1
kind: Service
metadata:
  name: fluvio-sc-internal
  labels:
    {{- include "fluvio.labels" . | nindent 4 }}
    app.kubernetes.io/component: sc
spec:
  type: ClusterIP
  selector:
    {{- include "fluvio.sc.selectorLabels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: 9004
    targetPort: 9004
