apiVersion: v1
kind: Service
metadata:
  name: fluvio-sc-public
  labels:
    {{- include "fluvio.labels" . | nindent 4 }}
    app.kubernetes.io/component: sc
  {{- with .Values.loadBalancer.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "fluvio.sc.selectorLabels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: {{ .Values.scPod.publicPort }}
    targetPort: {{ .Values.scPod.publicPort }}
